### ISSUE TITLE
特になにもしてないし、削除して問題なし

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/FizzBuzz#1]
https://github.com/yamaguchi-ryo/FizzBuzz/blob/2b08265287b48f41b53694f49c9e6024e99257f0/test/fizzbuzz/FizzBuzzTest.java#L20-L46

前処理、後処理とか何もしてないから今回は消しましょう

**Comment by yamaguchi-ryo** [comment]
削除しました。
