### ISSUE TITLE
お客様...？

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/FizzBuzz#2]
https://github.com/yamaguchi-ryo/FizzBuzz/blob/2b08265287b48f41b53694f49c9e6024e99257f0/test/fizzbuzz/FizzBuzzTest.java#L15

PCのユーザー名が表示されてる？
どうせなら自分の名前にしましょうか。

**Comment by yamaguchi-ryo** [comment]
自動生成で入力されていました。
他コメントアウト部分含め整理しました。
