### ISSUE TITLE
何点か

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/FizzBuzz#3]
https://github.com/yamaguchi-ryo/FizzBuzz/blob/2b08265287b48f41b53694f49c9e6024e99257f0/test/fizzbuzz/FizzBuzzTest.java#L48-L98

- System.out.printlnは要らんね。
- Javaのメソッド名に「_」は使わない
- テストメソッド名から何をテストするかが想像できない

上記について、対応ご検討ください。

**Comment by yamaguchi-ryo** [comment]
以下のように修正しました。
https://github.com/yamaguchi-ryo/FizzBuzz/blob/3ebd542fd553efdb0670e6487666030d302a0f96/test/fizzbuzz/FizzBuzzTest.java#L13-L15
